package:
  name: adrsm
  version: "0.9.1"

source:
  path: /Users/borry/Documents/GitHub/adrsm

requirements:
  run:
    - python 3.6.*
    - numpy
    - scipy
    - requests


test:
  source_files:
    - data
  commands:
    - adrsm --help

about:
  home: https://github.com/maxibor/adrsm
  license: MIT
  summary: 'Ancient DNA Read Simulator for Metagenomics'
