package:
  name: adrsm
  version: "0.8"

source:
  git_rev: "v0.8"
  git_url: https://github.com/maxibor/adrsm.git

requirements:
  run:
    - python 3.6.*
    - numpy
    - scipy
    - requests


test:
  commands:
    - adrsm --help

about:
  home: https://github.com/maxibor/adrsm
  license: MIT
  summary: 'Ancient DNA Read Simulator for Metagenomics'
